version: 1.0.{build}

environment:
  matrix:
    - generator: "MinGW Makefiles"
      boost_track: "master"
    - generator: "MinGW Makefiles"
      boost_track: "1.58.0"
    - generator: "MinGW Makefiles"
      boost_track: "1.57.0"
    - generator: "MinGW Makefiles"
      boost_track: "1.56.0"
    - generator: "MinGW Makefiles"
      boost_track: "1.55.0"

    - generator: "Visual Studio 12"
      boost_track: "master"
    - generator: "Visual Studio 12"
      boost_track: "1.58.0"
    - generator: "Visual Studio 12"
      boost_track: "1.57.0"
    - generator: "Visual Studio 12"
      boost_track: "1.56.0"
    - generator: "Visual Studio 12"
      boost_track: "1.55.0"


    - boost_track: "master"
    - boost_track: "1.58.0"
    - boost_track: "1.57.0"
    - boost_track: "1.56.0"
    - boost_track: "1.55.0"

configuration:
  - Debug
  - Release

install:
  - cinst biicode mingw
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\ProgramData\chocolatey\lib\cmake.3.0.2\content\cmake-3.0.2-win32-x86\bin
  - cmd: set PATH=%PATH:Git\bin=%;C:\MinGW\bin
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii;  
  - cmd: cmake --version
  - cmd: g++ --version
  - cmd: bii --version

build_script:
  - cmd: bii init -l
  - cmd: C:\MinGW\msys\1.0\bin\sh bootstrap.sh "%boost_track%"
  - cmd: C:\MinGW\msys\1.0\bin\sh generate "%boost_track%" --no-publish --ci-build
  - cmd: bii cpp:configure -G "%generator%" -DCMAKE_BUILD_TYPE="%configuration%"
  - cmd: bii cpp:build

test_script:
  - cmd: cd bin
  - cmd: for %%i in (*.exe) do start "" /b "%%i"
